export  const SITES_LOADING="SITES_LOADING";
export const ADD_SITES = "ADD_SITES";
export const SITES_FAILING="SITES_FAILING";
export const ADD_FLOORS="ADD_FLOORS";
export const ADD_SPACES="ADD_SPACES";
export const ADD_DESKS="ADD_DESKS";
export const LOADING_FLOORS="LOADING_FLOORS";
export const LOADING_SPACES="LOADING_SPACES";
export const LOADING_DESKS="LOADING_DESKS";
export const FLOORS_FAILED="FLOORS_FAILED";
export const DESKS_FAILED="FLOORS_FAILED";
export const SPACES_FAILED="SPACES_FAILED";
export const ADD_SIT="ADD_SIT";
export const SITS_FAILING="SITS_FAILING";
export const FETCH_SITS="FETCH_SITS";
export const SITS_LOADING="SITS_LOADING";
export const UPDATE_SITTING="UPDATE_SITTING";

